- platform: rest
  resource: https://youtube.googleapis.com/youtube/v3/channels?part=statistics&id=UCZQIVij87Slv02LeV7slFew&key=AIzaSyARUkzUP1bn99lhv1GLvcvH9MnXeW2wqwQ
  method: GET
  value_template: '{{ (value_json["items"][0].statistics.viewCount | int) }}'
  name: "YouTube Views"
  scan_interval: 900

- platform: rest
  resource: https://youtube.googleapis.com/youtube/v3/channels?part=statistics&id=UCZQIVij87Slv02LeV7slFew&key=AIzaSyARUkzUP1bn99lhv1GLvcvH9MnXeW2wqwQ
  value_template: '{{ (value_json["items"][0].statistics.subscriberCount | int) }}'
  name: "YouTube Subscribers"
  scan_interval: 900
